### ISSUE TITLE
get images in CSS files also

### ISSUE THREAD

**Issue by prabhakar267** [prabhakar267/image-extractor#3]

**Comment by mbad0la** [comment]
@prabhakar267 I'd like to take this up.

**Comment by prabhakar267** [comment]
@mbad0la okay!
Let me know if you face any problem.

**Comment by mbad0la** [comment]
@prabhakar267 how do we deal with relative paths for images and files? I guess the script assumes that the paths will be absolute at the moment.

**Comment by prabhakar267** [comment]
@mbad0la check this **if** condition
https://github.com/prabhakar267/image-extractor/blob/master/image-extractor.php#L71
